sns_config = {'axes.facecolor': '#ffffff',
              'axes.edgecolor': '#040404',
              'axes.grid': False,
              'axes.axisbelow': False,
              'axes.labelcolor': '#040404',
              'figure.facecolor': '#040404',
              'grid.color': '#040404',
              'grid.linestyle': '-',
              'text.color': '#040404',
              'xtick.color': '#040404',
              'ytick.color': '#040404',
              'xtick.direction': 'out',
              'ytick.direction': 'out',
              'lines.solid_capstyle': 'round',
              'patch.edgecolor': 'w',
              'patch.force_edgecolor': False,
              'image.cmap': 'rocket',
              'font.family': ['sans-serif'],
              'font.sans-serif': ['Arial',
                                  'DejaVu Sans',
                                  'Liberation Sans',
                                  'Bitstream Vera Sans',
                                  'sans-serif'],
              'xtick.bottom': False,
              'xtick.top': False,
              'ytick.left': False,
              'ytick.right': False,
              'axes.spines.left': False,
              'axes.spines.bottom': False,
              'axes.spines.right': False,
              'axes.spines.top': False
              }
